# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(602, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(20, 40, 561, 521))
        self.label_28.setStyleSheet("QLabel {\n"
"            background-color: #3C4052;\n"
"            padding: 12px;\n"
"            border-radius: 25px;\n"
"            border-bottom: 30px shadow;\n"
"        }")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(50, 150, 501, 391))
        self.label_29.setStyleSheet("QLabel {\n"
"            \n"
"    background-color: rgb(70, 74, 95);\n"
"            padding: 12px;\n"
"            border-radius: 25px;\n"
"            border-bottom: 30px shadow;\n"
"        }")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(50, 60, 501, 71))
        self.label_30.setStyleSheet("QLabel {\n"
"            \n"
"    background-color: rgb(70, 74, 95);\n"
"            padding: 12px;\n"
"            border-radius: 25px;\n"
"            border-bottom: 30px shadow;\n"
"        }")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 59, 501, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: gray")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(80, 180, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("QLabel {\n"
"            background-color: #595D75;\n"
"            padding: 12px;\n"
"            border-radius: 25px;\n"
"            border-bottom: 30px shadow;\n"
"            color: gray;\n"
"        }")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(360, 180, 151, 71))
        self.label_40.setStyleSheet("QLabel {\n"
"            background-color: rgb(60, 64, 82);\n"
"            padding: 12px;\n"
"            border-radius: 25px;\n"
"            border-bottom: 30px shadow;\n"
"        }")
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(360, 270, 151, 71))
        self.label_41.setStyleSheet("QLabel {\n"
"            background-color: rgb(60, 64, 82);\n"
"            padding: 12px;\n"
"            border-radius: 25px;\n"
"            border-bottom: 30px shadow;\n"
"        }")
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(80, 270, 251, 71))
        self.label_36.setStyleSheet("QLabel {\n"
"            background-color: #595D75;\n"
"            padding: 12px;\n"
"            border-radius: 25px;\n"
"            border-bottom: 30px shadow;\n"
"            color: gray;\n"
"        }")
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(360, 360, 151, 71))
        self.label_42.setStyleSheet("QLabel {\n"
"            background-color: rgb(60, 64, 82);\n"
"            padding: 12px;\n"
"            border-radius: 25px;\n"
"            border-bottom: 30px shadow;\n"
"        }")
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(80, 360, 251, 71))
        self.label_37.setStyleSheet("QLabel {\n"
"            background-color: #595D75;\n"
"            padding: 12px;\n"
"            border-radius: 25px;\n"
"            border-bottom: 30px shadow;\n"
"            color: gray;\n"
"        }")
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(360, 450, 151, 71))
        self.label_43.setStyleSheet("QLabel {\n"
"            background-color: rgb(60, 64, 82);\n"
"            padding: 12px;\n"
"            border-radius: 25px;\n"
"            border-bottom: 30px shadow;\n"
"        }")
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(80, 450, 251, 71))
        self.label_38.setStyleSheet("QLabel {\n"
"            background-color: #595D75;\n"
"            padding: 12px;\n"
"            border-radius: 25px;\n"
"            border-bottom: 30px shadow;\n"
"            color: gray;\n"
"        }")
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.app_install_frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.app_install_frame_1.setGeometry(QtCore.QRect(360, 180, 151, 71))
        self.app_install_frame_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.app_install_frame_1.setStyleSheet("QPushButton{\n"
"    padding: 12px;\n"
"    border-radius: 25px;\n"
"    border-bottom: 30px shadow;\n"
"}\n"
"QPushButton:pressed:hover{\n"
"    background-color: rgb(46, 49, 63);\n"
"    padding: 12px;\n"
"    border-radius: 25px;\n"
"    border-bottom: 30px shadow;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 64, 82);\n"
"    padding: 12px;\n"
"    border-radius: 25px;\n"
"    border-bottom: 30px shadow;\n"
"}")
        self.app_install_frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.app_install_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_install_frame_1.setLineWidth(0)
        self.app_install_frame_1.setObjectName("app_install_frame_1")
        self.cookies_toggle_layout = QtWidgets.QHBoxLayout(self.app_install_frame_1)
        self.cookies_toggle_layout.setContentsMargins(0, 0, 0, 0)
        self.cookies_toggle_layout.setSpacing(0)
        self.cookies_toggle_layout.setObjectName("cookies_toggle_layout")
        self.app_install_frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.app_install_frame_2.setGeometry(QtCore.QRect(360, 270, 151, 71))
        self.app_install_frame_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.app_install_frame_2.setStyleSheet("QPushButton{\n"
"    padding: 12px;\n"
"    border-radius: 25px;\n"
"    border-bottom: 30px shadow;\n"
"}\n"
"QPushButton:pressed:hover{\n"
"    background-color: rgb(46, 49, 63);\n"
"    padding: 12px;\n"
"    border-radius: 25px;\n"
"    border-bottom: 30px shadow;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 64, 82);\n"
"    padding: 12px;\n"
"    border-radius: 25px;\n"
"    border-bottom: 30px shadow;\n"
"}")
        self.app_install_frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.app_install_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_install_frame_2.setLineWidth(0)
        self.app_install_frame_2.setObjectName("app_install_frame_2")
        self.placeholder_toggle_layout_1 = QtWidgets.QHBoxLayout(self.app_install_frame_2)
        self.placeholder_toggle_layout_1.setContentsMargins(0, 0, 0, 0)
        self.placeholder_toggle_layout_1.setSpacing(0)
        self.placeholder_toggle_layout_1.setObjectName("placeholder_toggle_layout_1")
        self.app_install_frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.app_install_frame_3.setGeometry(QtCore.QRect(360, 360, 151, 71))
        self.app_install_frame_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.app_install_frame_3.setStyleSheet("QPushButton{\n"
"    padding: 12px;\n"
"    border-radius: 25px;\n"
"    border-bottom: 30px shadow;\n"
"}\n"
"QPushButton:pressed:hover{\n"
"    background-color: rgb(46, 49, 63);\n"
"    padding: 12px;\n"
"    border-radius: 25px;\n"
"    border-bottom: 30px shadow;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 64, 82);\n"
"    padding: 12px;\n"
"    border-radius: 25px;\n"
"    border-bottom: 30px shadow;\n"
"}")
        self.app_install_frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.app_install_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_install_frame_3.setLineWidth(0)
        self.app_install_frame_3.setObjectName("app_install_frame_3")
        self.placeholder_toggle_layout_2 = QtWidgets.QHBoxLayout(self.app_install_frame_3)
        self.placeholder_toggle_layout_2.setContentsMargins(0, 0, 0, 0)
        self.placeholder_toggle_layout_2.setSpacing(0)
        self.placeholder_toggle_layout_2.setObjectName("placeholder_toggle_layout_2")
        self.app_install_frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.app_install_frame_4.setGeometry(QtCore.QRect(360, 450, 151, 71))
        self.app_install_frame_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.app_install_frame_4.setStyleSheet("QPushButton{\n"
"    padding: 12px;\n"
"    border-radius: 25px;\n"
"    border-bottom: 30px shadow;\n"
"}\n"
"QPushButton:pressed:hover{\n"
"    background-color: rgb(46, 49, 63);\n"
"    padding: 12px;\n"
"    border-radius: 25px;\n"
"    border-bottom: 30px shadow;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 64, 82);\n"
"    padding: 12px;\n"
"    border-radius: 25px;\n"
"    border-bottom: 30px shadow;\n"
"}")
        self.app_install_frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.app_install_frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_install_frame_4.setLineWidth(0)
        self.app_install_frame_4.setObjectName("app_install_frame_4")
        self.placeholder_toggle_layout_3 = QtWidgets.QHBoxLayout(self.app_install_frame_4)
        self.placeholder_toggle_layout_3.setContentsMargins(0, 0, 0, 0)
        self.placeholder_toggle_layout_3.setSpacing(0)
        self.placeholder_toggle_layout_3.setObjectName("placeholder_toggle_layout_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Settings"))
        self.label_35.setText(_translate("MainWindow", "Enable cookies"))
